In [2]:
 import numpy as np
 list_ = [ '1' , '2' , '3' , '4' , '5' ]
 array_list = np.array(object = list_)

### ANSWER TO QUESTION 1:

#### Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
#### to print the data types of both the variables

In [13]:
print("the type of list_ Variable is:",type(list_))
print("the type of array_list variable is:",type(array_list))

the type of list_ Variable is: <class 'list'>
the type of array_list variable is: <class 'numpy.ndarray'>


### ANSWER TO QUESTION 2:

#### Write a code to print the data type of each and every element of both the variables list_ and 
#### arra_list

In [10]:
for i in list_:
    print("Element=",i,"type=",type(i))

Element= 1 type= <class 'str'>
Element= 2 type= <class 'str'>
Element= 3 type= <class 'str'>
Element= 4 type= <class 'str'>
Element= 5 type= <class 'str'>


In [11]:
for i in array_list:
     print("Element=",i,"type=",type(i))

Element= 1 type= <class 'numpy.str_'>
Element= 2 type= <class 'numpy.str_'>
Element= 3 type= <class 'numpy.str_'>
Element= 4 type= <class 'numpy.str_'>
Element= 5 type= <class 'numpy.str_'>


### ANSWER TO QUESTION 3:

In [14]:
####  Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
 
#### Will there be any difference in the data type of the elements present in both the variables, list_ and 
#### arra_list? If so then print the data types of each and every element present in both the variables

In [15]:
for i in list_:
    print("Element=",i,"type=",type(i))

Element= 1 type= <class 'str'>
Element= 2 type= <class 'str'>
Element= 3 type= <class 'str'>
Element= 4 type= <class 'str'>
Element= 5 type= <class 'str'>


In [16]:
for i in array_list:
     print("Element=",i,"type=",type(i))

Element= 1 type= <class 'numpy.int32'>
Element= 2 type= <class 'numpy.int32'>
Element= 3 type= <class 'numpy.int32'>
Element= 4 type= <class 'numpy.int32'>
Element= 5 type= <class 'numpy.int32'>


In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### ANSWER TO QUESTION 4:

#### Write a code to find the following characteristics of variable, num_array:
#### (i)	 shape
####
 (ii) siez

In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

### ANSWER TO QUESTION 5:

#### Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
#### creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).

In [24]:
import numpy as np
mat=np.zeros((3,3))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### ANSWER TO QUESTION 6:

#### Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
import numpy as np
mat=np.identity(5)
print(mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
